<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="7" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="46574" started-at="2019-09-18T07:41:04Z" finished-at="2019-09-18T07:41:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="46574" started-at="2019-09-18T07:41:04Z" finished-at="2019-09-18T07:41:50Z">
      <class name="test.LoginTest">
        <test-method status="PASS" signature="main()[pri:0, instance:test.LoginTest@3234e239]" name="main" duration-ms="14511" started-at="2019-09-18T07:41:04Z" finished-at="2019-09-18T07:41:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- main -->
        <test-method status="PASS" signature="verify2()[pri:1, instance:test.LoginTest@3234e239]" name="verify2" duration-ms="4085" started-at="2019-09-18T07:41:18Z" finished-at="2019-09-18T07:41:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify2 -->
        <test-method status="PASS" signature="verify3()[pri:2, instance:test.LoginTest@3234e239]" name="verify3" duration-ms="3720" started-at="2019-09-18T07:41:23Z" finished-at="2019-09-18T07:41:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify3 -->
        <test-method status="PASS" signature="verify4()[pri:3, instance:test.LoginTest@3234e239]" name="verify4" duration-ms="3767" started-at="2019-09-18T07:41:26Z" finished-at="2019-09-18T07:41:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify4 -->
        <test-method status="PASS" signature="verify5()[pri:4, instance:test.LoginTest@3234e239]" name="verify5" duration-ms="3554" started-at="2019-09-18T07:41:30Z" finished-at="2019-09-18T07:41:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify5 -->
        <test-method status="PASS" signature="verify6()[pri:5, instance:test.LoginTest@3234e239]" name="verify6" duration-ms="4757" started-at="2019-09-18T07:41:34Z" finished-at="2019-09-18T07:41:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify6 -->
        <test-method status="FAIL" signature="verify1()[pri:6, instance:test.LoginTest@3234e239]" name="verify1" duration-ms="9923" started-at="2019-09-18T07:41:38Z" finished-at="2019-09-18T07:41:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ARUN] but found [Admin - Attendance System]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ARUN] but found [Admin - Attendance System]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at test.LoginTest.verify1(LoginTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify1 -->
        <test-method status="PASS" signature="close()[pri:0, instance:test.LoginTest@3234e239]" name="close" is-config="true" duration-ms="2192" started-at="2019-09-18T07:41:48Z" finished-at="2019-09-18T07:41:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
